language: php

php:
  - 7.2
  - 7.3

cache:
  paths:
  - vendor/

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/codecept run
